source 'https://rubygems.org'

gem 'rails', '~> 4.2.1'
gem 'pg'
gem 'sass-rails', '~> 5.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc

gem 'rails_12factor', group: :production
gem 'puma'

# Dev and test.
group :development, :test do
  gem 'byebug'
  gem 'spring'
end
